### ISSUE TITLE
The last character may display at the second line

### ISSUE THREAD

**Issue by stevobm** [zumerlab/snapdom#42]
### What's this about?
- [x] I found a bug
- [ ] I have a feature idea

### Describe it simply:

The last character(In my case a Chinese character) may display at the second line.

Orininal:
<img width="362" alt="Image" src="https://github.com/user-attachments/assets/2b2cac4e-e231-497a-8fe3-44e68ecb3978" />
Snapshot:
<img width="274" alt="Image" src="https://github.com/user-attachments/assets/87c015be-2f6f-4ac5-acea-d3e48ad06346" />

**Comment by tinchox5** [comment]
Thank you for mentioning this issue. I have seen that before, so I will try to find a solution

**Comment by tinchox5** [comment]
@stevobm could you provide the html & css code of this code?

**Comment by stevobm** [comment]
> [@stevobm](https://github.com/stevobm) could you provide the html & css code of this code?

```html
        <div className="doc-preview-header">
          <div className="doc-date">{dateVisible && dateText}</div>
          <div className="user-name">{username}</div>
        </div>
```
```css
      .doc-preview-header{
        display: flex;
        flex-direction: row;
        align-items: center;
        font-size: 14px;
      }
      .doc-preview-header {
        padding: 20px 20px 0 20px;
        gap: 20px;
        justify-content: space-between;
        .user-name {
          font-weight: bold;
        }
      }
```
